# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbot2
import time

#mBot2を起動したときに以下の命令を実行する
@event.start
def on_start():

    #エンコーダモータEM1を30RPM, EM2を-10RPMで回転させる
    mbot2.drive_speed(30, -10)

    #ledを緑色に点灯させる
    cyberpi.led.on(1, 208, 19, "all")

    #3.5秒待つ
    time.sleep(3.5)

    #ledを消灯する

    cyberpi.led.off("all")

    #mBot2を50RPMで１秒間前進させる
    mbot2.forward(50, 1)

    #エンコーダモータEM1を10RPM, EM2を-30RPMで回転させる
    mbot2.drive_speed(10, -30)

    #ledを青色に点灯させる
    cyberpi.led.on(74, 1, 208, "all")

    #3.5秒待つ
    time.sleep(3.5)

    #ledを消灯させる
    cyberpi.led.off("all")

    #すべてのエンコーダモータを停止させる
    mbot2.EM_stop("ALL")
    #ledを赤色に点灯させる
    cyberpi.led.on(208, 2, 27, "all")

    #1秒待つ
    time.sleep(1)

    #ledを消灯させる
    cyberpi.led.on(0, 0, 0, "all")

