# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbuild, mbot2
# initialize variables
zhang_hai_wu_までの_ju_li_cn = 0

@event.start
def on_start():
    global zhang_hai_wu_までの_ju_li_cn
    while True:
      zhang_hai_wu_までの_ju_li_cn = mbuild.ultrasonic2.get(1)
      if zhang_hai_wu_までの_ju_li_cn < 10:
        mbot2.turn(-90)

      else:
        mbot2.forward(10)

